// Supabase client + realtime room channel setup.
//
// `utils/supabase/info.tsx` is autogenerated when the project is connected to
// Supabase and exports `projectId` and `publicAnonKey`.

import { createClient, type SupabaseClient, type RealtimeChannel } from '@supabase/supabase-js'
import { projectId, publicAnonKey } from '../../utils/supabase/info'

let cachedClient: SupabaseClient | null = null

const configured = Boolean(projectId && publicAnonKey)

export async function isSupabaseConfigured(): Promise<boolean> {
  return configured
}

export async function getSupabaseClient(): Promise<SupabaseClient | null> {
  if (!configured) return null
  if (!cachedClient) {
    cachedClient = createClient(`https://${projectId}.supabase.co`, publicAnonKey, {
      realtime: { params: { eventsPerSecond: 20 } },
    })
  }
  return cachedClient
}

/** Open a broadcast channel keyed by room code. */
export async function openRoomChannel(roomCode: string): Promise<RealtimeChannel | null> {
  const client = await getSupabaseClient()
  if (!client) return null
  return client.channel(`vadamvali:${roomCode}`, {
    config: { broadcast: { self: false }, presence: { key: crypto.randomUUID() } },
  })
}
